import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})

// Database types (will be generated by Prisma)
export type Database = {
  public: {
    Tables: {
      properties: {
        Row: {
          id: string
          title: string
          description: string
          price: number
          bedrooms: number
          bathrooms: number
          sqft: number
          address: string
          city: string
          state: string
          zip_code: string
          images: string[]
          features: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          price: number
          bedrooms: number
          bathrooms: number
          sqft: number
          address: string
          city: string
          state: string
          zip_code: string
          images?: string[]
          features?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          price?: number
          bedrooms?: number
          bathrooms?: number
          sqft?: number
          address?: string
          city?: string
          state?: string
          zip_code?: string
          images?: string[]
          features?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string
          user_type: 'buyer' | 'seller' | 'agent'
          preferences: any
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          full_name: string
          phone?: string
          user_type?: 'buyer' | 'seller' | 'agent'
          preferences?: any
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string
          user_type?: 'buyer' | 'seller' | 'agent'
          preferences?: any
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
} 